package com.whsolutions.core.mappings;

// Generated Jan 21, 2014 5:02:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PmsGroups generated by hbm2java
 */
@Entity
@Table(name = "pms_groups", catalog = "pms_storage", uniqueConstraints = @UniqueConstraint(columnNames = "group_name"))
public class PmsGroups implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3839291452365845541L;
	private int groupId;
	private Date creationDate;
	private String description;
	private String groupName;
	private Set<PmsUsers> pmsUserses = new HashSet<PmsUsers>(0);
	private Set<PmsMenusGroups> pmsMenusGroupses = new HashSet<PmsMenusGroups>(
			0);

	public PmsGroups() {
	}

	public PmsGroups(int groupId, Date creationDate, String groupName) {
		this.groupId = groupId;
		this.creationDate = creationDate;
		this.groupName = groupName;
	}

	public PmsGroups(int groupId, Date creationDate, String description,
			String groupName, Set<PmsUsers> pmsUserses,
			Set<PmsMenusGroups> pmsMenusGroupses) {
		this.groupId = groupId;
		this.creationDate = creationDate;
		this.description = description;
		this.groupName = groupName;
		this.pmsUserses = pmsUserses;
		this.pmsMenusGroupses = pmsMenusGroupses;
	}

	@Id
	@Column(name = "group_id", unique = true, nullable = false)
	public int getGroupId() {
		return this.groupId;
	}

	public void setGroupId(int groupId) {
		this.groupId = groupId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creation_date", nullable = false, length = 19)
	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "group_name", unique = true, nullable = false, length = 20)
	public String getGroupName() {
		return this.groupName;
	}

	public void setGroupName(String groupName) {
		this.groupName = groupName;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "pms_users_groups", catalog = "pms_storage", joinColumns = { @JoinColumn(name = "group_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) })
	public Set<PmsUsers> getPmsUserses() {
		return this.pmsUserses;
	}

	public void setPmsUserses(Set<PmsUsers> pmsUserses) {
		this.pmsUserses = pmsUserses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pmsGroups")
	public Set<PmsMenusGroups> getPmsMenusGroupses() {
		return this.pmsMenusGroupses;
	}

	public void setPmsMenusGroupses(Set<PmsMenusGroups> pmsMenusGroupses) {
		this.pmsMenusGroupses = pmsMenusGroupses;
	}

}
